---
driver:
  name: vagrant
  box_check_update: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[docker-server::00_setup]
      - recipe[docker-server::01_php]
    attributes:
